package com.radha.music;

import android.content.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;

/** Portable user-selected backup. Validates and stages input before touching live app data. */
public final class BackupStore {
    private static final String[] PREFS={"library","online","downloads"};
    private static final String[] DIRS={"downloads","artwork","lyrics"};
    private static JSONObject snapshot(Context c)throws JSONException {JSONObject all=new JSONObject();for(String name:PREFS){JSONObject values=new JSONObject();for(var item:c.getSharedPreferences(name,0).getAll().entrySet()){Object value=item.getValue();JSONObject field=new JSONObject();field.put("type",value instanceof Set?"set":value instanceof Boolean?"boolean":value instanceof Integer?"int":value instanceof Long?"long":value instanceof Float?"float":"string");field.put("value",value instanceof Set?new JSONArray((Set<?>)value):value);values.put(item.getKey(),field);}all.put(name,values);}return all;}
    public static void exportTo(Context c,OutputStream output)throws Exception {
        if(DownloadService.isBusy())throw new IOException("Finish or cancel active downloads first.");JSONObject manifest=new JSONObject().put("format","radha-backup").put("version",1).put("preferences",snapshot(c));
        try(ZipOutputStream zip=new ZipOutputStream(output)){zip.setLevel(1);zip.putNextEntry(new ZipEntry("manifest.json"));zip.write(manifest.toString().getBytes(StandardCharsets.UTF_8));zip.closeEntry();byte[] buffer=new byte[65536];for(String dir:DIRS){File[] files=new File(c.getFilesDir(),dir).listFiles();if(files==null)continue;for(File file:files){if(!file.isFile()||file.getName().endsWith(".part")||file.getName().endsWith(".tmp"))continue;zip.putNextEntry(new ZipEntry("files/"+dir+"/"+file.getName()));try(InputStream in=new FileInputStream(file)){int n;while((n=in.read(buffer))!=-1)zip.write(buffer,0,n);}zip.closeEntry();}}}
    }
    public static void importFrom(Context c,InputStream input)throws Exception {
        if(DownloadService.isBusy())throw new IOException("Finish or cancel active downloads first.");File stage=new File(c.getCacheDir(),"radha-import-"+UUID.randomUUID());if(!stage.mkdirs())throw new IOException("Could not prepare import");List<String> paths=new ArrayList<>();Set<String> names=new HashSet<>();JSONObject previous=snapshot(c);boolean applying=false;List<File[]> swapped=new ArrayList<>();
        try {
            try(ZipInputStream zip=new ZipInputStream(input)){ZipEntry entry;byte[] buffer=new byte[65536];long extracted=0,budget=Math.max(0,stage.getUsableSpace()-64L*1024*1024);while((entry=zip.getNextEntry())!=null){String name=entry.getName();if(!names.add(name)||names.size()>20000||!safeEntry(name))throw new IOException("Invalid backup entry");File target=new File(stage,name);target.getParentFile().mkdirs();long size=0;try(OutputStream out=new FileOutputStream(target)){int n;while((n=zip.read(buffer))!=-1){size+=n;extracted+=n;if(extracted>budget||(name.equals("manifest.json")&&size>8*1024*1024))throw new IOException("Backup exceeds available space or metadata limit");out.write(buffer,0,n);}}if(name.startsWith("files/"))paths.add(name);zip.closeEntry();}}
            File manifestFile=new File(stage,"manifest.json");if(!manifestFile.isFile())throw new IOException("Not a Radha backup");JSONObject manifest;try(InputStream in=new FileInputStream(manifestFile)){ByteArrayOutputStream bytes=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)bytes.write(b,0,n);manifest=new JSONObject(bytes.toString("UTF-8"));}
            if(!"radha-backup".equals(manifest.optString("format"))||manifest.optInt("version")!=1)throw new IOException("Unsupported backup version");JSONObject prefs=manifest.getJSONObject("preferences");validate(prefs);
            for(String path:paths){File source=new File(stage,path),dest=new File(c.getFilesDir(),path.substring(6)),old=new File(stage,"old/"+path.substring(6));dest.getParentFile().mkdirs();old.getParentFile().mkdirs();if(dest.exists()&&!dest.renameTo(old))throw new IOException("Could not preserve existing file");swapped.add(new File[]{dest,old});if(!source.renameTo(dest))throw new IOException("Could not restore file");}
            applying=true;restore(c,prefs,true);
        }catch(Exception failure){for(int i=swapped.size()-1;i>=0;i--){File[] pair=swapped.get(i);pair[0].delete();if(pair[1].exists())pair[1].renameTo(pair[0]);}if(applying)restore(c,previous,false);throw failure;}
        finally{deleteTree(stage);}
    }
    public static boolean safeEntry(String name){return name.equals("manifest.json")||name.matches("files/(downloads|artwork|lyrics)/[A-Za-z0-9_-]+\\.(media|jpg|json)");}
    private static void validate(JSONObject all)throws Exception {if(all.length()!=PREFS.length)throw new IOException("Invalid preference groups");for(String name:PREFS){JSONObject values=all.getJSONObject(name);Iterator<String> keys=values.keys();while(keys.hasNext()){JSONObject field=values.getJSONObject(keys.next());String type=field.getString("type");if(!Arrays.asList("set","boolean","int","long","float","string").contains(type))throw new IOException("Invalid preference value");Object v=field.get("value");if(type.equals("set")){JSONArray items=field.getJSONArray("value");for(int i=0;i<items.length();i++)if(!(items.get(i) instanceof String))throw new IOException("Invalid preference set");}else if(type.equals("string")&&!(v instanceof String)||type.equals("boolean")&&!(v instanceof Boolean)||Arrays.asList("int","long","float").contains(type)&&!(v instanceof Number))throw new IOException("Invalid preference type");}}}
    private static void restore(Context c,JSONObject all,boolean portable)throws Exception {for(String name:PREFS){SharedPreferences.Editor editor=c.getSharedPreferences(name,0).edit().clear();JSONObject values=all.getJSONObject(name);Iterator<String> keys=values.keys();while(keys.hasNext()){String key=keys.next();if(portable&&name.equals("library")&&key.equals("trees"))continue;JSONObject f=values.getJSONObject(key);switch(f.getString("type")){case "set":JSONArray a=f.getJSONArray("value");Set<String> set=new HashSet<>();for(int i=0;i<a.length();i++)set.add(a.getString(i));editor.putStringSet(key,set);break;case "boolean":editor.putBoolean(key,f.getBoolean("value"));break;case "int":editor.putInt(key,f.getInt("value"));break;case "long":editor.putLong(key,f.getLong("value"));break;case "float":editor.putFloat(key,(float)f.getDouble("value"));break;default:String value=f.getString("value");if(portable&&name.equals("downloads")&&key.startsWith("state:")&&(value.equals("Queued")||value.equals("Downloading")))value="Interrupted · tap to retry";editor.putString(key,value);}}if(!editor.commit())throw new IOException("Could not restore preferences");}}
    private static void deleteTree(File file){File[] children=file.listFiles();if(children!=null)for(File child:children)deleteTree(child);file.delete();}
}
