package com.radha.music;
import android.app.*;
import android.content.Context;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.function.BiConsumer;

public final class DownloadsDialog extends Dialog {
    private final DownloadStore store;private final Handler main=new Handler(Looper.getMainLooper());private final LinearLayout rows;private final BiConsumer<MediaEntry,List<MediaEntry>> play;private boolean closed;private String snapshot="";
    public DownloadsDialog(Activity activity,BiConsumer<MediaEntry,List<MediaEntry>> play){super(activity,android.R.style.Theme_Material_NoActionBar);this.play=play;store=new DownloadStore(activity);LinearLayout root=new LinearLayout(activity);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,32,24,24);root.setBackgroundColor(0xFF121315);TextView back=label("‹  Downloads",23);back.setPadding(12,20,12,24);back.setOnClickListener(v->dismiss());root.addView(back);TextView note=label("Only in Radha · music and videos",13);root.addView(note);ScrollView scroll=new ScrollView(activity);rows=new LinearLayout(activity);rows.setOrientation(LinearLayout.VERTICAL);scroll.addView(rows);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));TextView tip=label("Tap to play or retry · Hold to remove\nDownload progress and cancellation are in notifications.",12);root.addView(tip);TextView cancel=label("Cancel active downloads",16);cancel.setPadding(12,24,12,24);cancel.setTextColor(0xFFFF795F);cancel.setOnClickListener(v->{if(DownloadService.isBusy())getContext().startService(new android.content.Intent(getContext(),DownloadService.class).setAction("cancel"));});root.addView(cancel);setContentView(root);}
    private TextView label(String text,int size){TextView t=new TextView(getContext());t.setText(text);t.setTextSize(size);t.setTextColor(0xFFF8F6F2);return t;}
    @Override protected void onStart(){super.onStart();getWindow().setLayout(-1,-1);main.post(refresh);}
    private final Runnable refresh=new Runnable(){public void run(){if(closed)return;List<MediaEntry> entries=store.entries();StringBuilder value=new StringBuilder();for(MediaEntry e:entries)value.append(e.id).append(store.state(e.id));if(!value.toString().equals(snapshot)||rows.getChildCount()==0){snapshot=value.toString();rows.removeAllViews();if(entries.isEmpty())rows.addView(label("No downloads yet. Use a song or video’s ⋮ menu.",17));for(MediaEntry e:entries){String storedState=store.state(e.id);if((storedState.equals("Queued")||storedState.equals("Downloading"))&&!DownloadService.isBusy())store.state(e,"Interrupted · tap to retry");String state=store.state(e.id);TextView row=label(e.name+"\n"+(e.video?"Video":"Music")+" · "+state,16);row.setPadding(12,26,12,26);row.setOnClickListener(v->{if(store.files(e.id)!=null){List<MediaEntry> queue=new ArrayList<>();for(MediaEntry item:entries)if(item.video==e.video&&store.files(item.id)!=null)queue.add(item);dismiss();play.accept(e,queue);}else{DownloadService.start(getContext(),e);}});row.setOnLongClickListener(v->{if(state.equals("Downloading")||state.equals("Queued")){Toast.makeText(getContext(),"Cancel active downloads in notifications first",Toast.LENGTH_SHORT).show();return true;}new AlertDialog.Builder(getContext()).setTitle("Remove download?").setMessage(e.name).setPositiveButton("Remove",(d,w)->{store.remove(e.id);snapshot="";}).setNegativeButton("Keep",null).show();return true;});rows.addView(row);}}main.postDelayed(this,1000);}};
    @Override public void dismiss(){closed=true;main.removeCallbacksAndMessages(null);super.dismiss();}
}
