package com.radha.music;
import android.app.*;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.media3.common.*;
import androidx.media3.exoplayer.ExoPlayer;
import java.util.*;
import java.util.concurrent.*;

@androidx.annotation.OptIn(markerClass=androidx.media3.common.util.UnstableApi.class)
public final class LyricsDialog extends Dialog {
    private final ExoPlayer player;private final Handler main=new Handler(Looper.getMainLooper());private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final LinearLayout root,lines;private final ScrollView scroll;private final TextView title,artist,position,duration;private final ImageView cover;private final MainActivity.Symbol toggle;private final SeekBar progress;private final ArtworkStore artwork;
    private final List<TextView> labels=new ArrayList<>();private List<LyricsRules.Line> synced=Collections.emptyList();private String id="";private int token,index=-2;private boolean closed,seeking;private long manualUntil;
    public LyricsDialog(Activity activity,ExoPlayer player){super(activity,android.R.style.Theme_Material_NoActionBar);this.player=player;artwork=new ArtworkStore(activity);root=column();root.setBackgroundColor(0xFF101113);root.setPadding(dp(20),dp(12),dp(20),dp(18));
        LinearLayout header=new LinearLayout(activity);header.setGravity(Gravity.CENTER_VERTICAL);header.addView(control("back",this::dismiss),new LinearLayout.LayoutParams(dp(44),dp(48)));cover=new ImageView(activity);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);header.addView(cover,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout info=column();info.setPadding(dp(12),0,0,0);title=text("Lyrics",16);title.setSingleLine();title.setEllipsize(android.text.TextUtils.TruncateAt.END);artist=text("",12);artist.setTextColor(0xFFA4A4A6);info.addView(title);info.addView(artist);header.addView(info,new LinearLayout.LayoutParams(0,-2,1));root.addView(header);
        scroll=new ScrollView(activity);scroll.setVerticalScrollBarEnabled(false);lines=column();lines.setPadding(0,dp(52),0,dp(80));scroll.addView(lines);scroll.setOnTouchListener((v,e)->{manualUntil=System.currentTimeMillis()+8000;return false;});root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout trackerPanel=column();GradientDrawable panelBackground=new GradientDrawable();panelBackground.setColor(0xFF1C1D20);panelBackground.setCornerRadius(dp(20));trackerPanel.setBackground(panelBackground);trackerPanel.setPadding(dp(16),dp(12),dp(16),dp(8));root.addView(trackerPanel);progress=new SeekBar(activity);progress.setMax(1000);progress.setContentDescription("Song progress. Drag to seek");progress.setMinimumHeight(dp(48));progress.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(0xFF66666C));progress.setProgressTintList(android.content.res.ColorStateList.valueOf(0xFFFF795F));progress.setThumbTintList(android.content.res.ColorStateList.valueOf(0xFFFF795F));TextView tracker=text("Song progress",12);tracker.setTextColor(0xFFA4A4A6);trackerPanel.addView(tracker);trackerPanel.addView(progress,new LinearLayout.LayoutParams(-1,dp(48)));progress.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){seeking=true;}public void onStopTrackingTouch(SeekBar s){if(player.getDuration()>0)player.seekTo(player.getDuration()*s.getProgress()/1000);seeking=false;}public void onProgressChanged(SeekBar s,int p,boolean user){if(user&&player.getDuration()>0)position.setText(clock(player.getDuration()*p/1000));}});
        position=text("",11);position.setTextColor(0xFFA4A4A6);LinearLayout time=new LinearLayout(activity);time.addView(position,new LinearLayout.LayoutParams(0,-2,1));duration=text("",11);duration.setTextColor(0xFFA4A4A6);time.addView(duration);trackerPanel.addView(time);
        LinearLayout transport=new LinearLayout(activity);transport.setGravity(Gravity.CENTER);transport.addView(control("previous",()->{if(player.hasPreviousMediaItem())player.seekToPreviousMediaItem();else player.seekTo(0);}),new LinearLayout.LayoutParams(dp(76),dp(80)));FrameLayout play=control("play",()->{if(player.getPlayWhenReady())player.pause();else player.play();});toggle=(MainActivity.Symbol)play.getChildAt(0);GradientDrawable coral=new GradientDrawable();coral.setColor(0xFFFF795F);coral.setCornerRadius(dp(40));play.setBackground(coral);transport.addView(play,new LinearLayout.LayoutParams(dp(64),dp(64)));transport.addView(control("skip",()->{if(player.hasNextMediaItem())player.seekToNextMediaItem();}),new LinearLayout.LayoutParams(dp(76),dp(80)));trackerPanel.addView(transport);TextView source=text("Lyrics · LRCLIB",10);source.setTextColor(0xFF77787B);source.setGravity(Gravity.CENTER);trackerPanel.addView(source);TextView credit=text("Created, designed and developed by Diwash Bhatta",10);credit.setTextColor(0xFFA4A4A6);credit.setGravity(Gravity.CENTER);credit.setPadding(0,dp(12),0,0);root.addView(credit);setContentView(root);
    }
    private int dp(int n){return Math.round(n*getContext().getResources().getDisplayMetrics().density);}private LinearLayout column(){LinearLayout v=new LinearLayout(getContext());v.setOrientation(LinearLayout.VERTICAL);return v;}
    private TextView text(String s,int size){TextView t=new TextView(getContext());t.setText(s);t.setTextSize(size);t.setTextColor(0xFFF8F6F2);return t;}
    private FrameLayout control(String kind,Runnable run){FrameLayout frame=new FrameLayout(getContext());frame.setContentDescription(kind);frame.addView(new MainActivity.Symbol(getContext(),kind,0xFFF8F6F2),new FrameLayout.LayoutParams(dp(26),dp(26),Gravity.CENTER));frame.setOnClickListener(v->run.run());return frame;}
    @Override protected void onStart(){super.onStart();getWindow().setLayout(-1,-1);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);main.post(tick);}
    private final Runnable tick=new Runnable(){public void run(){if(closed)return;MediaItem item=player.getCurrentMediaItem();if(item!=null&&!id.equals(item.mediaId)){id=item.mediaId;load(item);}toggle.kind=player.getPlayWhenReady()?"pause":"play";toggle.invalidate();if(!seeking)position.setText(clock(player.getCurrentPosition()));duration.setText(clock(player.getDuration()));if(!seeking)progress.setProgress(player.getDuration()>0?(int)(1000*player.getCurrentPosition()/player.getDuration()):0);int selected=LyricsRules.current(synced,player.getCurrentPosition());if(selected!=index){index=selected;for(int i=0;i<labels.size();i++){TextView line=labels.get(i);line.setTextColor(i==index?0xFFF8F6F2:0xFF77787B);line.setTypeface(null,i==index?Typeface.BOLD:Typeface.NORMAL);GradientDrawable marker=new GradientDrawable();marker.setColor(i==index?0xFFFF795F:0x00000000);marker.setBounds(0,0,dp(3),dp(48));line.setCompoundDrawables(marker,null,null,null);line.setCompoundDrawablePadding(dp(12));}if(index>=0&&index<labels.size()&&System.currentTimeMillis()>manualUntil)scroll.smoothScrollTo(0,Math.max(0,labels.get(index).getTop()-scroll.getHeight()/3));}main.postDelayed(this,350);}};
    private static String clock(long ms){long seconds=Math.max(0,ms/1000);return String.format(Locale.US,"%d:%02d",seconds/60,seconds%60);}
    private void load(MediaItem item){int generation=++token;title.setText(String.valueOf(item.mediaMetadata.title));artist.setText(String.valueOf(item.mediaMetadata.artist));lines.removeAllViews();labels.clear();synced=Collections.emptyList();index=-2;lines.addView(new RadhaLoadingView(getContext()),new LinearLayout.LayoutParams(-1,dp(40)));
        MediaEntry entry=new MediaEntry(item.mediaId,String.valueOf(item.mediaMetadata.title),"",String.valueOf(item.mediaMetadata.artist),false,Math.max(0,player.getDuration()),0,item.mediaMetadata.artworkUri==null?"":item.mediaMetadata.artworkUri.toString());artwork.load(entry,b->{if(closed||generation!=token)return;cover.setImageBitmap(b);if(b!=null){int color=b.getPixel(b.getWidth()/2,b.getHeight()/2);int tint=android.graphics.Color.rgb(android.graphics.Color.red(color)/5,android.graphics.Color.green(color)/5,android.graphics.Color.blue(color)/5);root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xFF101113,tint,0xFF101113}));}});
        worker.submit(()->{try{LyricsClient.Lyrics lyric=LyricsClient.fetch(getContext().getApplicationContext(),entry);main.post(()->{if(closed||generation!=token)return;if(!LyricsAvailability.usable(lyric)){dismiss();return;}lines.removeAllViews();synced=lyric.lines();if(!synced.isEmpty()){for(LyricsRules.Line l:synced){TextView t=text(l.text(),21);t.setTypeface(null,Typeface.NORMAL);t.setPadding(0,dp(18),0,dp(18));t.setLineSpacing(dp(4),1);t.setOnClickListener(v->player.seekTo(l.time()));labels.add(t);lines.addView(t);}}else{TextView t=text(lyric.instrumental()?"Instrumental · no lyrics":lyric.plain().isEmpty()?"Lyrics aren’t available for this song yet.":lyric.plain(),21);t.setLineSpacing(dp(16),1);lines.addView(t);}index=-2;scroll.scrollTo(0,0);});}catch(Exception error){main.post(()->{if(closed||generation!=token)return;lines.removeAllViews();lines.addView(text("Lyrics unavailable. Tap to retry.",18));lines.setOnClickListener(v->load(item));});}});
    }
    @Override public void dismiss(){closed=true;token++;main.removeCallbacksAndMessages(null);worker.shutdownNow();artwork.close();super.dismiss();}
}
