package com.radha.music;

import android.app.*;
import android.content.*;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.media3.common.*;
import androidx.media3.exoplayer.ExoPlayer;
import java.util.*;

@androidx.annotation.OptIn(markerClass=androidx.media3.common.util.UnstableApi.class)
final class QueueDialog extends Dialog {
    private final ExoPlayer player;private final ArtworkStore artwork;private final LinearLayout body,footer;private final TextView count;private final Handler main=new Handler(Looper.getMainLooper());private MainActivity.Symbol pause;private ProgressBar progress, currentProgress;private TextView currentTime;private boolean closed;
    QueueDialog(Activity activity,ExoPlayer player,ArtworkStore artwork){super(activity,android.R.style.Theme_Material_NoActionBar);this.player=player;this.artwork=artwork;
        LinearLayout root=column();root.setBackgroundColor(0xFF101113);root.setPadding(dp(16),dp(12),dp(16),dp(16));LinearLayout header=row();header.addView(icon("back",this::dismiss));LinearLayout title=column();title.addView(text("Up next",22,0xFFF8F6F2));count=text("",12,0xFFA4A4A6);title.addView(count);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));header.addView(icon("more",()->new AlertDialog.Builder(getContext()).setTitle("Queue").setItems(new String[]{"Clear upcoming songs"},(d,w)->{List<Integer> remove=upcoming(player);remove.sort(Comparator.reverseOrder());for(int index:remove)player.removeMediaItem(index);}).setNegativeButton("Cancel",null).show()));root.addView(header);
        ScrollView scroll=new ScrollView(activity);scroll.setVerticalScrollBarEnabled(false);body=column();scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));footer=column();root.addView(footer);TextView credit=text("Created, designed and developed by Diwash Bhatta",10,0xFFA4A4A6);credit.setGravity(Gravity.CENTER);credit.setPadding(0,dp(12),0,0);root.addView(credit);setContentView(root);player.addListener(listener);render();
    }
    private int dp(int n){return Math.round(n*getContext().getResources().getDisplayMetrics().density);}private LinearLayout column(){LinearLayout l=new LinearLayout(getContext());l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(getContext());l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private TextView text(String s,int size,int color){TextView t=new TextView(getContext());t.setText(s);t.setTextSize(size);t.setTextColor(color);return t;}
    private GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(14));return d;}
    private FrameLayout icon(String name,Runnable run){FrameLayout f=new FrameLayout(getContext());f.setContentDescription(name);f.addView(new MainActivity.Symbol(getContext(),name,0xFFF8F6F2),new FrameLayout.LayoutParams(dp(23),dp(23),Gravity.CENTER));f.setLayoutParams(new LinearLayout.LayoutParams(dp(44),dp(48)));f.setOnClickListener(v->run.run());return f;}
    private ImageView cover(MediaItem item){ImageView image=new ImageView(getContext());image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(shape(0xFF26282D));image.setClipToOutline(true);String url=item.mediaMetadata.artworkUri==null?"":item.mediaMetadata.artworkUri.toString();MediaEntry entry=new MediaEntry(item.mediaId,String.valueOf(item.mediaMetadata.title),"",String.valueOf(item.mediaMetadata.artist),false,0,0,url);artwork.load(entry,b->{if(!closed)image.setImageBitmap(b);});return image;}
    private View labels(MediaItem item){LinearLayout labels=column();labels.setPadding(dp(10),0,dp(4),0);TextView title=text(String.valueOf(item.mediaMetadata.title),14,0xFFF8F6F2);title.setSingleLine();title.setEllipsize(android.text.TextUtils.TruncateAt.END);labels.addView(title);TextView artist=text(String.valueOf(item.mediaMetadata.artist),11,0xFFA4A4A6);artist.setSingleLine();labels.addView(artist);return labels;}
    static List<Integer> upcoming(Player player){List<Integer> indices=new ArrayList<>();Timeline timeline=player.getCurrentTimeline();int at=player.getCurrentMediaItemIndex();if(at<0||timeline.isEmpty())return indices;for(int n=0;n<player.getMediaItemCount();n++){at=timeline.getNextWindowIndex(at,Player.REPEAT_MODE_OFF,player.getShuffleModeEnabled());if(at==C.INDEX_UNSET)break;indices.add(at);}return indices;}
    private void render(){if(closed)return;body.removeAllViews();footer.removeAllViews();count.setText(player.getMediaItemCount()+" songs");MediaItem current=player.getCurrentMediaItem();if(current==null){body.addView(text("Your queue is empty",18,0xFFA4A4A6));return;}
        LinearLayout card=row();card.setPadding(dp(10),dp(12),dp(10),dp(12));card.setBackground(shape(0xFF1C1D20));card.addView(cover(current),new LinearLayout.LayoutParams(dp(64),dp(64)));card.addView(labels(current),new LinearLayout.LayoutParams(0,-2,1));TextView playing=text("♫",24,0xFFFF795F);playing.setContentDescription("Now playing");card.addView(playing);LinearLayout playingCard=column();playingCard.setBackground(shape(0xFF1C1D20));playingCard.addView(card);currentProgress=new ProgressBar(getContext(),null,android.R.attr.progressBarStyleHorizontal);currentProgress.setMax(1000);currentProgress.setProgressTintList(android.content.res.ColorStateList.valueOf(0xFFFF795F));playingCard.addView(currentProgress,new LinearLayout.LayoutParams(-1,dp(3)));currentTime=text("",10,0xFFA4A4A6);currentTime.setPadding(dp(10),dp(4),dp(10),dp(8));playingCard.addView(currentTime);body.addView(playingCard);LinearLayout heading=row();TextView next=text("Next in queue",18,0xFFF8F6F2);next.setPadding(0,dp(18),0,dp(14));heading.addView(next,new LinearLayout.LayoutParams(0,-2,1));FrameLayout shuffle=icon("shuffle",()->player.setShuffleModeEnabled(!player.getShuffleModeEnabled()));shuffle.setAlpha(player.getShuffleModeEnabled()?1f:.55f);heading.addView(shuffle);body.addView(heading);
        List<Integer> nextIndices=upcoming(player);for(int order=0;order<nextIndices.size();order++){int index=nextIndices.get(order);MediaItem item=player.getMediaItemAt(index);LinearLayout line=row();line.setPadding(0,dp(8),0,dp(8));if(order==0)line.setBackground(shape(0xFF302421));TextView drag=text("⠿",22,0xFFA4A4A6);drag.setGravity(Gravity.CENTER);drag.setContentDescription("Hold to reorder "+item.mediaMetadata.title);line.addView(drag,new LinearLayout.LayoutParams(dp(32),dp(48)));line.addView(cover(item),new LinearLayout.LayoutParams(dp(46),dp(46)));line.addView(labels(item),new LinearLayout.LayoutParams(0,-2,1));if(order==0){TextView badge=text("NEXT",9,0xFFFF795F);line.addView(badge);}long length=item.mediaMetadata.extras==null?0:item.mediaMetadata.extras.getLong("duration");if(length>0){TextView duration=text(clock(length),10,0xFFA4A4A6);duration.setPadding(dp(4),0,0,0);line.addView(duration);}line.addView(icon("more",()->menu(index)));line.setOnClickListener(v->{player.seekTo(index,0);player.play();});drag.setOnLongClickListener(v->{v.startDragAndDrop(ClipData.newPlainText("Radha queue",index+"|"+item.mediaId),new View.DragShadowBuilder(line),null,0);return true;});line.setOnDragListener((v,event)->{if(event.getAction()==DragEvent.ACTION_DRAG_STARTED)return event.getClipDescription()!=null&&"Radha queue".contentEquals(event.getClipDescription().getLabel());if(event.getAction()==DragEvent.ACTION_DROP){try{String[] data=event.getClipData().getItemAt(0).getText().toString().split("\\|",2);int from=Integer.parseInt(data[0]);if(data.length!=2||from<0||from>=player.getMediaItemCount()||!player.getMediaItemAt(from).mediaId.equals(data[1]))return false;if(from>=0&&from<player.getMediaItemCount()&&index<player.getMediaItemCount()){if(player.getShuffleModeEnabled())player.setShuffleModeEnabled(false);player.moveMediaItem(from,index);}}catch(RuntimeException ignored){}return true;}return true;});body.addView(line);}
        if(nextIndices.isEmpty())body.addView(text("End of queue · add a song with Play next",14,0xFFA4A4A6));LinearLayout mini=row();mini.setBackground(shape(0xFF1C1D20));mini.setPadding(dp(8),dp(8),0,dp(8));mini.addView(cover(current),new LinearLayout.LayoutParams(dp(42),dp(42)));mini.addView(labels(current),new LinearLayout.LayoutParams(0,-2,1));FrameLayout play=icon("pause",()->{if(player.getPlayWhenReady())player.pause();else player.play();});pause=(MainActivity.Symbol)play.getChildAt(0);mini.addView(play);mini.addView(icon("skip",()->{if(player.hasNextMediaItem())player.seekToNextMediaItem();}));footer.addView(mini);progress=new ProgressBar(getContext(),null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(0xFFFF795F));footer.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));
    }
    private void menu(int index){if(index>=player.getMediaItemCount())return;new AlertDialog.Builder(getContext()).setTitle(String.valueOf(player.getMediaItemAt(index).mediaMetadata.title)).setItems(new String[]{"Play now","Move up","Remove from queue"},(d,w)->{if(index>=player.getMediaItemCount())return;if(w==0){player.seekTo(index,0);player.play();}else if(w==1){if(player.getShuffleModeEnabled())player.setShuffleModeEnabled(false);player.moveMediaItem(index,Math.min(player.getMediaItemCount()-1,Math.max(player.getCurrentMediaItemIndex()+1,index-1)));}else player.removeMediaItem(index);}).show();}
    private final Player.Listener listener=new Player.Listener(){@Override public void onEvents(Player p,Player.Events events){if(events.contains(Player.EVENT_TIMELINE_CHANGED)||events.contains(Player.EVENT_MEDIA_ITEM_TRANSITION)||events.contains(Player.EVENT_SHUFFLE_MODE_ENABLED_CHANGED))render();}};
    @Override protected void onStart(){super.onStart();getWindow().setLayout(-1,-1);getWindow().getDecorView().setSystemUiVisibility(5894);main.post(tick);}
    private static String clock(long ms){long seconds=Math.max(0,ms/1000);return String.format(Locale.US,"%d:%02d",seconds/60,seconds%60);}
    private final Runnable tick=new Runnable(){public void run(){if(closed)return;if(pause!=null){pause.kind=player.getPlayWhenReady()?"pause":"play";pause.invalidate();}if(progress!=null)progress.setProgress(player.getDuration()>0?(int)(player.getCurrentPosition()*1000/player.getDuration()):0);if(currentProgress!=null&&progress!=null)currentProgress.setProgress(progress.getProgress());if(currentTime!=null)currentTime.setText(clock(player.getCurrentPosition())+" / "+clock(player.getDuration()));main.postDelayed(this,500);}};
    @Override public void dismiss(){closed=true;main.removeCallbacksAndMessages(null);player.removeListener(listener);super.dismiss();}
}
